version: '3.9'

services:
  tornadoblue:
    build: .
#    command: npm run dev
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.tornadoblue.rule=Host(`tornadoblue.com`)
      - traefik.http.routers.tornadoblue.entrypoints=web,websecure
      - traefik.http.routers.tornadoblue.tls.certresolver=letsencrypt
      - traefik.http.services.tornadoblue.loadbalancer.server.port=80

networks:
  traefik:
    external: true
